"""LLM context packs.

The bridge between the deterministic layer and Copilot. Each pack is a small,
self-contained Markdown/JSON file holding *only verified facts* extracted from
the graph. Copilot is instructed to read these instead of guessing at the raw
XML, which is what keeps generated reports free of invented components.

Packs are intentionally small (a few KB each) so several fit in one prompt.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

from ..analysis.inventory import (
    complexity_ranking, dead_code, entry_points, error_handling_gaps,
    hotspots, integration_surface, migration_sequence, module_dependencies,
    module_metrics, circular_dependencies, tier_distribution,
)
from ..model import Graph, GraphNode
from .markdown import table_lines as _table


class ContextPackBuilder:
    """Writes the `context/` folder consumed by the Copilot prompts."""

    def __init__(self, graph: Graph, output_dir: Path):
        self.graph = graph
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    def build_all(self) -> Dict[str, str]:
        written: Dict[str, str] = {}
        written['project-facts.md'] = self._write('project-facts.md', self.project_facts())
        written['entry-points.md'] = self._write('entry-points.md', self.entry_point_pack())
        written['complexity.md'] = self._write('complexity.md', self.complexity_pack())
        written['dead-code.md'] = self._write('dead-code.md', self.dead_code_pack())
        written['integration-surface.md'] = self._write(
            'integration-surface.md', self.integration_pack())
        written['data-contracts.md'] = self._write('data-contracts.md', self.contract_pack())
        written['migration-sequence.md'] = self._write(
            'migration-sequence.md', self.sequence_pack())
        written['facts.json'] = self._write_json('facts.json', self.facts_json())

        proc_dir = self.output_dir / 'processes'
        proc_dir.mkdir(exist_ok=True)
        top = sorted(self.graph.by_label('BWProcess'),
                     key=lambda p: -float(p.properties.get('complexityScore', 0) or 0))[:25]
        for proc in top:
            name = f"processes/{proc.name.replace('/', '_')}.md"
            written[name] = self._write(name, self.process_pack(proc))

        written['MANIFEST.md'] = self._write('MANIFEST.md', self._manifest(written))
        return written

    # ------------------------------------------------------------------
    def _write(self, rel: str, content: str) -> str:
        path = self.output_dir / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding='utf-8')
        return str(path)

    def _write_json(self, rel: str, data: Any) -> str:
        path = self.output_dir / rel
        path.write_text(json.dumps(data, indent=2, default=str), encoding='utf-8')
        return str(path)

    # ------------------------------------------------------------------
    def project_facts(self) -> str:
        stats = self.graph.stats()
        meta = self.graph.meta or {}
        lines = [
            '# Project Facts (verified)',
            '',
            'Generated by the deterministic analyzer. Every number below is a count of',
            'artefacts that exist on disk. Cite this file rather than estimating.',
            '',
            f"- **Source root:** `{meta.get('tibcoRoot', 'n/a')}`",
            f"- **Generated:** {meta.get('generatedAt', 'n/a')}",
            f"- **Modules:** {', '.join(meta.get('modules', [])) or 'n/a'}",
            '',
            '## Graph totals',
            '',
        ]
        lines += _table(['Metric', 'Value'],
                        [['Nodes', stats['totalNodes']],
                         ['Relationships', stats['totalRelationships']]])
        lines += ['', '## Nodes by label', '']
        lines += _table(['Label', 'Count'], [[k, v] for k, v in stats['nodeCounts'].items()])
        lines += ['', '## Relationships by type', '']
        lines += _table(['Type', 'Count'],
                        [[k, v] for k, v in stats['relationshipCounts'].items()])
        lines += ['', '## Files discovered', '']
        lines += _table(['Artefact family', 'Files'],
                        [[k, v] for k, v in (meta.get('artifactFamilies') or {}).items()])
        lines += ['', '## Complexity tiers', '']
        lines += _table(['Tier', 'Processes'],
                        [[k, v] for k, v in tier_distribution(self.graph).items()])
        lines += ['', '## Modules', '']
        mods = module_metrics(self.graph)
        lines += _table(['Module', 'Processes', 'Activities', 'Schemas', 'Services',
                         'Entry points', 'Total complexity'],
                        [[m['module'], m['processes'], m['activities'], m['schemas'],
                          m['services'], m['entryPoints'], m['totalComplexity']] for m in mods])
        deps = module_dependencies(self.graph)
        if deps:
            lines += ['', '## Cross-module dependencies', '']
            lines += _table(['From', 'To', 'Calls'],
                            [[d['from'], d['to'], d['calls']] for d in deps])
        return '\n'.join(lines) + '\n'

    def entry_point_pack(self) -> str:
        rows = entry_points(self.graph)
        lines = ['# Entry Point Catalog (verified)', '',
                 'Every externally reachable surface found in the source tree.', '']
        lines += _table(['Process', 'Entry type', 'Spring Boot target', 'Endpoint',
                         'Module', 'Tier', 'Score', 'File'],
                        [[r['process'], r['entryType'], r['springTarget'],
                          r['endpoint'] or '-', r['module'], r['tier'],
                          r['complexityScore'], f"`{r['filePath']}`"] for r in rows])
        if not rows:
            lines.append('_No entry points detected._')
        return '\n'.join(lines) + '\n'

    def complexity_pack(self) -> str:
        rows = complexity_ranking(self.graph)
        gaps = error_handling_gaps(self.graph)
        hot = hotspots(self.graph)
        cycles = circular_dependencies(self.graph)
        lines = ['# Complexity & Risk (verified)', '',
                 'complexity = activities + 0.5x transitions + 3x error handlers '
                 '+ 2x groups + 0.5x schema refs', '',
                 '## Process ranking', '']
        lines += _table(['#', 'Process', 'Module', 'Tier', 'Score', 'Activities',
                         'Transitions', 'Error handlers', 'Schemas', 'Called by'],
                        [[i, r['process'], r['module'], r['tier'], r['score'],
                          r['activities'], r['transitions'], r['errorHandlers'],
                          r['schemas'], r['calledBy']]
                         for i, r in enumerate(rows[:40], 1)])
        lines += ['', '## Change hotspots (highest blast radius)', '']
        lines += _table(['Type', 'Name', 'Module', 'Dependents', 'Relations'],
                        [[h['type'], h['name'], h['module'], h['dependents'],
                          ', '.join(h['relationTypes'])] for h in hot])
        lines += ['', '## Processes without error handling', '']
        lines += _table(['Process', 'Module', 'Activities', 'Tier', 'Entry type'],
                        [[g['process'], g['module'], g['activities'], g['tier'],
                          g['entryType']] for g in gaps[:25]]) if gaps else ['_None._']
        lines += ['', '## Circular dependencies', '']
        if cycles:
            for cycle in cycles[:20]:
                lines.append(f"- `{' -> '.join(cycle)}`")
        else:
            lines.append('_None detected._')
        return '\n'.join(lines) + '\n'

    def dead_code_pack(self) -> str:
        dc = dead_code(self.graph)
        lines = ['# Dead Code Inventory (verified)', '',
                 'Artefacts nothing in the scanned tree references. Confirm against '
                 'deployment descriptors before deleting - a reference may live outside '
                 'the scanned scope.', '']
        titles = {
            'orphanSchemas': 'Orphan schemas (no USES_XSD / IMPORTS_SCHEMA)',
            'unreachableProcesses': 'Unreachable processes (no caller, no entry point)',
            'unusedSharedResources': 'Unused shared resources',
            'unusedServices': 'Unreferenced service contracts',
            'unreferencedTransformations': 'Unreferenced transformations',
        }
        total = 0
        for key, title in titles.items():
            rows = dc.get(key, [])
            total += len(rows)
            lines += ['', f'## {title} ({len(rows)})', '']
            if rows:
                headers = sorted({k for r in rows for k in r})
                lines += _table(headers, [[r.get(h, '') for h in headers] for r in rows])
            else:
                lines.append('_None found._')
        lines += ['', f'**Total unreferenced artefacts: {total}**']
        if total == 0:
            lines.append('')
            lines.append('No dead code detected - every artefact is referenced.')
        return '\n'.join(lines) + '\n'

    def integration_pack(self) -> str:
        rows = integration_surface(self.graph)
        lines = ['# Integration Surface (verified)', '',
                 'Every activity that crosses the process boundary, with its Spring target.',
                 '']
        lines += _table(['Category', 'Spring target', 'Occurrences', 'Processes'],
                        [[r['category'], r['springTarget'], r['count'],
                          ', '.join(r['processes'][:8])] for r in rows]) if rows else ['_None._']
        lines += ['', '## Shared resources → external systems', '']
        res_rows = []
        for res in self.graph.by_label('SharedResource'):
            targets = [self.graph.nodes[r.end_id].name
                       for r in self.graph.outgoing(res.node_id)
                       if r.rel_type == 'CONNECTS_TO' and r.end_id in self.graph.nodes]
            users = [self.graph.nodes[r.start_id].name
                     for r in self.graph.incoming(res.node_id)
                     if r.rel_type == 'REFERENCES' and r.start_id in self.graph.nodes]
            res_rows.append([res.name, res.properties.get('resourceType', ''),
                             res.properties.get('springEquivalent', ''),
                             ', '.join(targets) or '-', len(users)])
        lines += _table(['Resource', 'Type', 'Spring equivalent', 'Connects to', 'Used by'],
                        res_rows) if res_rows else ['_None._']

        gvars = self.graph.by_label('GlobalVariable')
        lines += ['', '## Global variables (future application.yml)', '']
        lines += _table(['Variable', 'Value', 'Module'],
                        [[g.name, str(g.properties.get('value', ''))[:60], g.module]
                         for g in gvars[:60]]) if gvars else ['_None._']
        return '\n'.join(lines) + '\n'

    def contract_pack(self) -> str:
        lines = ['# Data Contracts (verified)', '',
                 'Schemas and their consumers. These contracts must be preserved '
                 'byte-for-byte during migration.', '']
        rows = []
        for xsd in sorted(self.graph.by_label('XSD'), key=lambda x: x.name):
            users = [self.graph.nodes[r.start_id].name
                     for r in self.graph.incoming(xsd.node_id)
                     if r.rel_type in ('USES_XSD', 'IMPORTS_SCHEMA') and r.start_id in self.graph.nodes]
            rows.append([xsd.name, xsd.properties.get('namespace', ''),
                         xsd.properties.get('elementCount', 0),
                         xsd.properties.get('rootElements', ''),
                         len(users), ', '.join(sorted(set(users))[:6]) or '-',
                         f"`{xsd.file_path}`"])
        lines += _table(['Schema', 'Namespace', 'Elements', 'Root elements',
                         'Consumers', 'Used by', 'File'], rows) if rows else ['_None._']

        services = self.graph.by_label('Service')
        if services:
            lines += ['', '## Service contracts (WSDL)', '']
            svc_rows = []
            for svc in services:
                ops = [self.graph.nodes[r.end_id].name
                       for r in self.graph.outgoing(svc.node_id)
                       if r.rel_type == 'EXPOSES' and r.end_id in self.graph.nodes]
                svc_rows.append([svc.name, svc.properties.get('namespace', ''),
                                 svc.properties.get('bindingStyle', ''),
                                 svc.properties.get('endpointUrl', ''),
                                 ', '.join(ops[:8]) or '-',
                                 svc.properties.get('springEquivalent', '')])
            lines += _table(['Service', 'Namespace', 'Binding', 'Endpoint',
                             'Operations', 'Spring target'], svc_rows)
        return '\n'.join(lines) + '\n'

    def sequence_pack(self) -> str:
        waves = migration_sequence(self.graph)
        lines = ['# Dependency-ordered Migration Sequence (verified)', '',
                 'Wave N depends only on processes migrated in waves < N. '
                 'Within a wave, processes are ordered by ascending complexity.', '']
        for wave in waves:
            lines += ['', f"## Wave {wave['wave']}"
                          + (f" — {wave['note']}" if wave['note'] else ''), '']
            lines += _table(['Process', 'Module', 'Tier', 'Score', 'Entry type'],
                            [[p['process'], p['module'], p['tier'], p['score'],
                              p['entryType']] for p in wave['processes']])
        if not waves:
            lines.append('_No processes to sequence._')
        return '\n'.join(lines) + '\n'

    def process_pack(self, proc: GraphNode) -> str:
        """Per-process subgraph: everything an LLM needs about one process."""
        out = self.graph.outgoing(proc.node_id)
        inn = self.graph.incoming(proc.node_id)
        activities = sorted(
            [self.graph.nodes[r.end_id] for r in out
             if r.rel_type == 'EXECUTES' and r.end_id in self.graph.nodes],
            key=lambda a: int(a.properties.get('order', 0) or 0))
        schemas = [self.graph.nodes[r.end_id] for r in out
                   if r.rel_type == 'USES_XSD' and r.end_id in self.graph.nodes]
        resources = [self.graph.nodes[r.end_id] for r in out
                     if r.rel_type == 'REFERENCES' and r.end_id in self.graph.nodes]
        callers = [self.graph.nodes[r.start_id] for r in inn
                   if r.rel_type == 'CALLS' and r.start_id in self.graph.nodes]

        lines = [f'# Process: {proc.name}', '',
                 f"- **File:** `{proc.file_path}`",
                 f"- **Module:** {proc.module}",
                 f"- **Entry type:** {proc.properties.get('entryType', 'NONE')}",
                 f"- **Complexity:** {proc.properties.get('complexityScore', 0)} "
                 f"({proc.properties.get('tier', '')})",
                 f"- **Target namespace:** `{proc.properties.get('targetNamespace', '')}`",
                 '', '## Activities (execution order)', '']
        lines += _table(['#', 'Activity', 'Category', 'TIBCO type', 'Spring equivalent'],
                        [[a.properties.get('order', ''), a.name,
                          a.properties.get('category', ''),
                          f"`{a.properties.get('rawType', '')}`",
                          a.properties.get('springEquivalent', '')] for a in activities])

        transitions = [r for r in self.graph.rels
                       if r.rel_type == 'TRANSITIONS_TO'
                       and r.start_id in {a.node_id for a in activities}]
        if transitions:
            lines += ['', '## Control flow', '']
            lines += _table(['From', 'To', 'Condition type', 'Condition'],
                            [[self.graph.nodes[r.start_id].name,
                              self.graph.nodes[r.end_id].name if r.end_id in self.graph.nodes else r.end_id,
                              r.properties.get('conditionType', 'always'),
                              f"`{str(r.properties.get('condition', ''))[:80]}`"]
                             for r in transitions])
        if schemas:
            lines += ['', '## Schemas used', '']
            lines += _table(['Schema', 'Namespace', 'Elements', 'File'],
                            [[s.name, s.properties.get('namespace', ''),
                              s.properties.get('elementCount', 0), f"`{s.file_path}`"]
                             for s in schemas])
        if resources:
            lines += ['', '## Shared resources', '']
            lines += _table(['Resource', 'Type', 'Spring equivalent'],
                            [[r.name, r.properties.get('resourceType', ''),
                              r.properties.get('springEquivalent', '')] for r in resources])
        if callers:
            lines += ['', '## Called by', '']
            for c in callers:
                owner = self.graph.node(str(c.properties.get('processRef', '')))
                lines.append(f"- {c.name}" + (f" (in {owner.name})" if owner else ''))
        return '\n'.join(lines) + '\n'

    def facts_json(self) -> Dict[str, Any]:
        return {
            'stats': self.graph.stats(),
            'meta': self.graph.meta,
            'entryPoints': entry_points(self.graph),
            'tierDistribution': tier_distribution(self.graph),
            'complexityTop': complexity_ranking(self.graph)[:50],
            'deadCode': dead_code(self.graph),
            'hotspots': hotspots(self.graph),
            'modules': module_metrics(self.graph),
            'moduleDependencies': module_dependencies(self.graph),
            'circularDependencies': circular_dependencies(self.graph),
            'integrationSurface': integration_surface(self.graph),
            'migrationSequence': migration_sequence(self.graph),
        }

    def _manifest(self, written: Dict[str, str]) -> str:
        lines = ['# Context Pack Manifest', '',
                 'Ground-truth files for LLM analysis. Read the pack that matches your',
                 'question; do not re-derive these facts from raw XML.', '',
                 '| Pack | Use it for |', '|------|-----------|',
                 '| `project-facts.md` | Totals, modules, artefact counts, tier mix |',
                 '| `entry-points.md` | Every externally reachable surface + Spring target |',
                 '| `complexity.md` | Ranking, hotspots, error-handling gaps, cycles |',
                 '| `dead-code.md` | Unreferenced artefacts to exclude from scope |',
                 '| `integration-surface.md` | Outbound integrations, resources, global variables |',
                 '| `data-contracts.md` | Schemas, namespaces, consumers, WSDL operations |',
                 '| `migration-sequence.md` | Dependency-ordered migration waves |',
                 '| `processes/<name>.md` | Full subgraph for one process |',
                 '| `facts.json` | Same facts, machine-readable |',
                 '', '## Files', '']
        for name in sorted(written):
            lines.append(f'- `{name}`')
        return '\n'.join(lines) + '\n'
