"""Report scaffolding.

The analyzer writes the *facts* half of each step report — tables, counts,
diagrams, checklists — and leaves explicitly marked `<!-- LLM: ... -->` slots
for the narrative half. Copilot fills those slots and nothing else, so the
numbers in a delivered report can always be traced back to a parse.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from ..analysis.inventory import full_inventory
from ..diagrams import mermaid
from ..model import Graph
from .markdown import table_lines

LLM_MARK = ('<!-- LLM: {instruction} -->\n'
            '_(pending narrative — generated by the Copilot prompt for this step)_\n')


def _table(headers: List[str], rows: List[List[Any]]) -> str:
    if not rows:
        return '_No data._\n'
    return '\n'.join(table_lines(headers, rows)) + '\n'


def _header(title: str, step: str, graph: Graph) -> str:
    meta = graph.meta or {}
    return '\n'.join([
        f'# {title}',
        '',
        f'> **Step:** {step}  ',
        f'> **Source:** `{meta.get("tibcoRoot", "n/a")}`  ',
        f'> **Analyzer run:** {meta.get("generatedAt", "n/a")}  ',
        f'> **Report scaffolded:** {datetime.now(timezone.utc).isoformat()}  ',
        '> **Provenance:** every table below is generated from the parsed knowledge '
        'graph. Narrative sections marked `LLM` are written by Copilot from these '
        'facts only.',
        '',
    ])


# ──────────────────────────────────────────────────────────────
def step00_graph_analysis(graph: Graph, inv: Dict[str, Any]) -> str:
    stats = inv['stats']
    out = [_header('Step 00 — TIBCO Graph Analysis Report',
                   'Phase 1 / Step 0 — Neo4j Analysis', graph)]
    out.append('## 1. Executive Summary\n')
    out.append(LLM_MARK.format(instruction=(
        'Summarise the estate in 5-8 sentences using ONLY the tables in this report: '
        'size, dominant entry-point style, complexity concentration, the top three '
        'migration risks, and the recommended first wave. Cite counts explicitly.')))

    out.append('\n## 2. Graph Statistics\n')
    out.append(_table(['Metric', 'Value'],
                      [['Total nodes', stats['totalNodes']],
                       ['Total relationships', stats['totalRelationships']],
                       ['Node labels', len(stats['nodeCounts'])],
                       ['Relationship types', len(stats['relationshipCounts'])]]))
    out.append('\n### Nodes by label\n')
    out.append(_table(['Label', 'Count'], [[k, v] for k, v in stats['nodeCounts'].items()]))
    out.append('\n### Relationships by type\n')
    out.append(_table(['Type', 'Count'],
                      [[k, v] for k, v in stats['relationshipCounts'].items()]))

    out.append('\n## 3. Artefact Inventory\n')
    out.append(_table(['Artefact family', 'Files'],
                      [[k, v] for k, v in (graph.meta.get('artifactFamilies') or {}).items()]))

    out.append('\n## 4. Complexity Ranking\n')
    out.append(_table(['#', 'Process', 'Module', 'Tier', 'Score', 'Activities',
                       'Transitions', 'Error handlers', 'Schemas', 'Called by'],
                      [[i, r['process'], r['module'], r['tier'], r['score'],
                        r['activities'], r['transitions'], r['errorHandlers'],
                        r['schemas'], r['calledBy']]
                       for i, r in enumerate(inv['complexity']['ranking'][:40], 1)]))
    out.append('\n### Tier distribution\n')
    out.append(_table(['Tier', 'Processes'],
                      [[k, v] for k, v in inv['complexity']['tierDistribution'].items()]))

    out.append('\n## 5. Entry Point Catalog\n')
    out.append(_table(['Process', 'Entry type', 'Spring Boot target', 'Endpoint', 'Module', 'Tier'],
                      [[e['process'], e['entryType'], e['springTarget'],
                        e['endpoint'] or '-', e['module'], e['tier']]
                       for e in inv['entryPoints']]))

    out.append('\n## 6. Change Hotspots (blast-radius ranking)\n')
    out.append(_table(['Type', 'Name', 'Module', 'Dependents', 'Relation types'],
                      [[h['type'], h['name'], h['module'], h['dependents'],
                        ', '.join(h['relationTypes'])] for h in inv['hotspots']]))

    out.append('\n## 7. Dead Code Inventory\n')
    totals = inv['deadCodeTotals']
    out.append(_table(['Category', 'Count'], [[k, v] for k, v in totals.items()]))
    for key, rows in inv['deadCode'].items():
        out.append(f'\n### {key} ({len(rows)})\n')
        if rows:
            headers = sorted({k for r in rows for k in r})
            out.append(_table(headers, [[r.get(h, '') for h in headers] for r in rows]))
        else:
            out.append('_None found._\n')
    if sum(totals.values()) == 0:
        out.append('\nNo dead code detected — every artefact is referenced.\n')

    out.append('\n## 8. Circular Dependencies (migration blockers)\n')
    cycles = inv['circularDependencies']
    if cycles:
        for cycle in cycles[:25]:
            out.append(f"- `{' -> '.join(cycle)}`\n")
    else:
        out.append('_None detected._\n')

    out.append('\n## 9. Recommended Migration Sequence\n')
    for wave in inv['migrationSequence']:
        out.append(f"\n### Wave {wave['wave']}"
                   + (f" — {wave['note']}" if wave['note'] else '') + '\n')
        out.append(_table(['Process', 'Module', 'Tier', 'Score', 'Entry type'],
                          [[p['process'], p['module'], p['tier'], p['score'],
                            p['entryType']] for p in wave['processes']]))

    out.append('\n## 10. Migration Risk Assessment\n')
    out.append(LLM_MARK.format(instruction=(
        'For each Critical/High tier process and each top-5 hotspot, state the specific '
        'migration risk and the mitigation. Reference only artefacts named above.')))

    out.append('\n## 11. Neo4j Import & Verification\n')
    out.append('Artefacts produced alongside this report:\n\n'
               '- `neo4j_nodes.csv`, `neo4j_relationships.csv` — admin-import pair\n'
               '- `neo4j_import.cypher` — runnable in Neo4j Browser / cypher-shell\n'
               '- `analysis_queries.cypher` — verification and analysis cookbook\n'
               '- `validation_report.md` — referential-integrity gate result\n\n'
               '```bash\n'
               'neo4j-admin database import full \\\n'
               '  --nodes=neo4j_nodes.csv \\\n'
               '  --relationships=neo4j_relationships.csv \\\n'
               '  --database=tibco-migration --overwrite-destination\n'
               '```\n')

    out.append('\n## 12. Migration Readiness Checklist\n')
    out.append(_table(['Deliverable', 'Status', 'Evidence'], [
        ['Knowledge graph built', 'DONE', f"{stats['totalNodes']} nodes / {stats['totalRelationships']} rels"],
        ['Neo4j CSV + Cypher exported', 'DONE', 'neo4j_nodes.csv, neo4j_relationships.csv, neo4j_import.cypher'],
        ['Graph validated', 'DONE', 'validation_report.md'],
        ['Complexity scored', 'DONE', f"{len(inv['complexity']['ranking'])} processes"],
        ['Entry points catalogued', 'DONE', f"{len(inv['entryPoints'])} entry points"],
        ['Dead code inventoried', 'DONE', f"{sum(totals.values())} unreferenced artefacts"],
        ['Migration sequence proposed', 'DONE', f"{len(inv['migrationSequence'])} waves"],
        ['Risk narrative written', 'PENDING LLM', 'Section 10'],
        ['Executive summary written', 'PENDING LLM', 'Section 1'],
    ]))
    return ''.join(out)


# ──────────────────────────────────────────────────────────────
def step01_architecture_diagrams(graph: Graph, inv: Dict[str, Any]) -> str:
    out = [_header('Step 01 — Architecture Diagrams Report',
                   'Phase 1 / Step 1 — Architecture Diagrams', graph)]
    out.append('## 1. Validation Methodology\n')
    out.append('Every element in every diagram below was emitted from a parsed artefact.\n'
               'No component, relationship or pattern was assumed. Diagram sources live in\n'
               '`generated_diagrams/` and regenerate deterministically from the same graph.\n')
    out.append('\n| Check | Result |\n|---|---|\n')
    out.append(f"| Components traced to source files | {len(graph.nodes)} nodes, "
               f"all from parsed XML |\n")
    out.append(f"| Relationships with code evidence | {len(graph.rels)} edges |\n")
    out.append('| Assumed/placeholder components | 0 |\n')
    out.append('| Remote PlantUML includes | 0 (offline-safe syntax only) |\n')

    out.append('\n## 2. System Context\n\n```mermaid\n')
    out.append(mermaid.context_diagram(graph))
    out.append('\n```\n')

    out.append('\n## 3. Container View (modules)\n\n```mermaid\n')
    out.append(mermaid.container_diagram(graph))
    out.append('\n```\n')

    out.append('\n## 4. Component View\n\n```mermaid\n')
    out.append(mermaid.component_diagram(graph))
    out.append('\n```\n')

    out.append('\n## 5. Process Dependency Graph\n\n```mermaid\n')
    out.append(mermaid.dependency_graph(graph))
    out.append('\n```\n')

    out.append('\n## 6. Schema Usage Map\n\n```mermaid\n')
    out.append(mermaid.schema_usage_map(graph))
    out.append('\n```\n')

    out.append('\n## 7. Canonical Data Model (ER)\n\n```mermaid\n')
    out.append(mermaid.er_diagram(graph))
    out.append('\n```\n')

    out.append('\n## 8. Integration Surface\n\n```mermaid\n')
    out.append(mermaid.integration_diagram(graph))
    out.append('\n```\n')

    top = sorted(graph.by_label('BWProcess'),
                 key=lambda p: -float(p.properties.get('complexityScore', 0) or 0))[:5]
    out.append('\n## 9. Key Process Flows\n')
    for proc in top:
        out.append(f'\n### {proc.name}\n\n```mermaid\n')
        out.append(mermaid.process_flow(graph, proc))
        out.append('\n```\n')

    out.append('\n## 10. Architecture Commentary\n')
    out.append(LLM_MARK.format(instruction=(
        'Explain what the diagrams above reveal: coupling patterns, layering violations, '
        'candidate service boundaries for the Spring Boot target, and which flows deserve '
        'a sequence diagram in the design phase. Reference only components drawn above.')))
    return ''.join(out)


# ──────────────────────────────────────────────────────────────
def step02_discover_baseline(graph: Graph, inv: Dict[str, Any]) -> str:
    out = [_header('Step 02 — Discover & Baseline Report',
                   'Phase 1 / Step 2 — Discover & Baseline', graph)]

    out.append('## 1. Artefact Inventory\n')
    out.append(_table(['Artefact family', 'Files'],
                      [[k, v] for k, v in (graph.meta.get('artifactFamilies') or {}).items()]))
    out.append('\n### By module\n')
    out.append(_table(['Module', 'Processes', 'Activities', 'Schemas', 'Services',
                       'Global vars', 'Shared resources', 'Entry points', 'Complexity'],
                      [[m['module'], m['processes'], m['activities'], m['schemas'],
                        m['services'], m['globalVariables'], m['sharedResources'],
                        m['entryPoints'], m['totalComplexity']] for m in inv['modules']]))

    out.append('\n## 2. Entry Points → Spring Boot Targets\n')
    out.append(_table(['Process', 'Entry type', 'Spring Boot target', 'Endpoint', 'Module'],
                      [[e['process'], e['entryType'], e['springTarget'],
                        e['endpoint'] or '-', e['module']] for e in inv['entryPoints']]))

    out.append('\n## 3. Adapter / Integration Inventory\n')
    out.append(_table(['Category', 'Spring Boot equivalent', 'Occurrences', 'Processes'],
                      [[r['category'], r['springTarget'], r['count'],
                        ', '.join(r['processes'][:6])] for r in inv['integrationSurface']]))

    out.append('\n## 4. Canonical Schema Catalog (contract freeze)\n')
    rows = []
    for xsd in sorted(graph.by_label('XSD'), key=lambda x: x.name):
        users = [graph.nodes[r.start_id].name for r in graph.incoming(xsd.node_id)
                 if r.rel_type in ('USES_XSD', 'IMPORTS_SCHEMA') and r.start_id in graph.nodes]
        rows.append([xsd.name, xsd.properties.get('namespace', ''),
                     xsd.properties.get('elementCount', 0),
                     xsd.properties.get('rootElements', ''), len(users),
                     f"`{xsd.file_path}`"])
    out.append(_table(['Schema', 'Namespace', 'Elements', 'Root elements', 'Consumers', 'File'],
                      rows))
    out.append('\n> **Contract freeze rule:** none of the namespaces or element names above '
               'may change during migration. They are the acceptance criteria for parity '
               'testing.\n')

    out.append('\n## 5. Configuration Surface (global variables)\n')
    gvars = graph.by_label('GlobalVariable')
    out.append(_table(['Variable', 'Default value', 'Module', 'Type'],
                      [[g.name, str(g.properties.get('value', ''))[:60], g.module,
                        g.properties.get('type', '')] for g in gvars[:80]]))

    out.append('\n## 6. Error Handling Baseline\n')
    out.append(_table(['Process', 'Module', 'Activities', 'Tier', 'Entry type'],
                      [[g['process'], g['module'], g['activities'], g['tier'],
                        g['entryType']] for g in inv['errorHandlingGaps'][:30]]))
    out.append('\n_Processes listed above have no error transition; the target Spring '
               'service must define explicit behaviour for their failure paths._\n')

    out.append('\n## 7. Dead Code / Out-of-Scope Candidates\n')
    out.append(_table(['Category', 'Count'],
                      [[k, v] for k, v in inv['deadCodeTotals'].items()]))

    out.append('\n## 8. Business Flow Documentation\n')
    out.append(LLM_MARK.format(instruction=(
        'For each entry point in section 2, describe the happy path, the branching '
        'conditions and the fault paths, using the per-process context packs in '
        '`context/processes/`. Do not describe a process you have not opened.')))

    out.append('\n## 9. Risk Register\n')
    out.append(LLM_MARK.format(instruction=(
        'Build a risk table (risk / likelihood / impact / mitigation / owner) from the '
        'hotspots, cycles, error-handling gaps and integration surface above.')))

    out.append('\n## 10. Success Criteria\n')
    out.append(LLM_MARK.format(instruction=(
        'Define measurable parity criteria per entry point: contract preservation, '
        'latency budget, throughput, error-rate parity, test coverage targets.')))

    out.append('\n## 11. Prioritised Migration Backlog\n')
    for wave in inv['migrationSequence']:
        out.append(f"\n### Wave {wave['wave']}\n")
        out.append(_table(['Process', 'Module', 'Tier', 'Score', 'Entry type'],
                          [[p['process'], p['module'], p['tier'], p['score'],
                            p['entryType']] for p in wave['processes']]))
    return ''.join(out)


REPORTS = {
    'Step00_TIBCO_ANALYSIS_REPORT.md': step00_graph_analysis,
    'Step01_ARCHITECTURE_DIAGRAMS_REPORT.md': step01_architecture_diagrams,
    'Step02_DISCOVER_AND_BASELINE_REPORT.md': step02_discover_baseline,
}


def generate_reports(graph: Graph, output_dir: Path,
                     inventory: Dict[str, Any] | None = None) -> Dict[str, str]:
    inv = inventory if inventory is not None else full_inventory(graph)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    written = {}
    for name, fn in REPORTS.items():
        path = output_dir / name
        path.write_text(fn(graph, inv), encoding='utf-8')
        written[name] = str(path)
    return written
