"""Report scaffolds for the federated estate.

The tables are generated and must not be hand-edited; the sections marked
`<!-- LLM: ... -->` are where narrative belongs. That split is the same one the
other three analyzers use: numbers come from the graph, judgement comes from
the analyst, and the marker stays in place so the next run can tell them apart.
"""
from __future__ import annotations

from typing import Any, Dict, List

from analyzer_core.model import Graph

from ..analysis.inventory import (boundary_components, contended_tables,
                                  estates, hotspots, issues_summary, summary,
                                  table_access)
from ..analysis.sequence import render_markdown as sequence_markdown
from ..analysis.sequence import sequence
from ..constants import MIN_DATASOURCE_COVERAGE, MIN_SQL_BIND_COVERAGE


def _table(headers: List[str], rows: List[List[Any]]) -> List[str]:
    if not rows:
        return ['_None._']
    out = ['| ' + ' | '.join(headers) + ' |',
           '|' + '|'.join(['---'] * len(headers)) + '|']
    for row in rows:
        out.append('| ' + ' | '.join('' if v is None else str(v) for v in row) + ' |')
    return out


def _provenance(graph: Graph) -> List[str]:
    meta = graph.meta or {}
    links = meta.get('links') or {}
    return [
        '> Generated by `estate-analyze` from three finished analyses. No '
        'source tree was parsed to produce this report.',
        '>',
        f"> Estate map: `{links.get('estateMap') or 'none supplied'}`  |  "
        f"bare-name matches: {'admitted' if links.get('allowNameMatch') else 'suppressed'}"
        f"  |  generated {meta.get('generatedAt', '')}",
        '',
    ]


def step00_federation(graph: Graph) -> str:
    counts = summary(graph)
    coverage = (graph.meta or {}).get('coverage') or {}
    out = ['# Step 00 — Federated Estate Graph', '']
    out += _provenance(graph)
    out += ['## What was joined', '']
    out += _table(['Estate', 'Title', 'Nodes', 'Relationships', 'Own coverage',
                   'Source root'],
                  [[r['estate'], r['title'], r['nodes'], r['relationships'],
                    r['coverage'], r['sourceRoot']] for r in estates(graph)])
    out += ['', '## The join', '']
    out += _table(['Metric', 'Value', 'Meaning'], [
        ['Shared database nodes', coverage.get('mergedDbNodes', 0),
         'Merged on natural key alone. No heuristic, no confidence score.'],
        ['Inferred cross-estate links', coverage.get('crossEstateLinks', 0),
         f"By basis: {coverage.get('crossEstateLinksByBasis', {})}"],
        ['SQL bind coverage', f"{coverage.get('sqlBindCoverage', 0)}%",
         f"{coverage.get('jdbcActivitiesBound', 0)} of "
         f"{coverage.get('jdbcActivitiesWithSql', 0)} JDBC activities carrying "
         f'static SQL resolved to a database object.'],
        ['Datasource coverage', f"{coverage.get('datasourceCoverage', 0)}%",
         f"{coverage.get('datasourcesMapped', 0)} of "
         f"{coverage.get('datasources', 0)} JDBC resources mapped to a schema."],
        ['No static SQL', coverage.get('noStaticSqlSites', 0),
         'Activities that build SQL at runtime. Invisible by design, recorded '
         'not hidden.'],
        ['Unbound references', coverage.get('unboundReferences', 0),
         'Named a table no database estate models, or reached it through an '
         'unmapped datasource.'],
    ])
    if coverage.get('sqlBindCoverage', 0) < MIN_SQL_BIND_COVERAGE or \
            coverage.get('datasourceCoverage', 0) < MIN_DATASOURCE_COVERAGE:
        out += ['', '> **This graph is provisional.** At least one coverage '
                    'gate is unmet, so any statement about what an estate does '
                    'or does not touch must carry that caveat.', '']
    out += ['', '## Size', '']
    out += _table(['Metric', 'Count'], [[k, v] for k, v in counts.items()])
    out += ['', '## Interpretation', '',
            '<!-- LLM: what does the shape of this estate imply? Which estate '
            'is the centre of gravity, and which is peripheral? Ground every '
            'claim in the tables above. -->', '']
    return '\n'.join(out) + '\n'


def step01_dependency(graph: Graph) -> str:
    out = ['# Step 01 — Cross-Estate Dependencies', '']
    out += _provenance(graph)
    out += ['## Shared data', '']
    out += _table(['Object', 'Label', 'Estates', 'Written by', 'Read by'],
                  [[r['name'], r['label'], r['estateCount'],
                    ', '.join(r['writerEstates']) or '-',
                    ', '.join(r['readerEstates']) or '-']
                   for r in table_access(graph) if r['estateCount'] > 1])
    out += ['', '## Contended objects', '',
            'Written by more than one estate. Each of these is a cutover '
            'constraint, not just a dependency.', '']
    out += _table(['Object', 'Written by', 'Read by'],
                  [[r['name'], ', '.join(r['writerEstates']),
                    ', '.join(r['readerEstates']) or '-']
                   for r in contended_tables(graph)])
    out += ['', '## Components touching data another estate uses', '']
    out += _table(['Estate', 'Label', 'Component', 'Reaches', 'Access',
                   'Min confidence'],
                  [[r['estate'], r['label'], r['name'], ', '.join(r['reaches']),
                    ', '.join(r['access']), r['minConfidence']]
                   for r in boundary_components(graph)])
    out += ['', '## Most depended-upon across estates', '']
    out += _table(['Label', 'Name', 'Estate', 'Fan-in', 'Depended on by'],
                  [[r['label'], r['name'], r['estate'], r['fanIn'],
                    ', '.join(r['estates'])] for r in hotspots(graph)])
    out += ['', '## Interpretation', '',
            '<!-- LLM: which dependencies would a single-estate analysis have '
            'missed, and what would that have cost? Name the components, cite '
            'the confidence, and say which links still need confirming by '
            'hand. -->', '']
    return '\n'.join(out) + '\n'


def step02_risk_and_sequence(graph: Graph) -> str:
    result = issues_summary(graph)
    out = ['# Step 02 — End-to-End Risk and Sequence', '']
    out += _provenance(graph)
    out += ['## Findings', '']
    out += _table(['Dimension', 'Breakdown'],
                  [['Severity', result['bySeverity']],
                   ['Category', result['byCategory']],
                   ['Estate', result['byEstate']]])
    out += ['', '### Cross-estate findings', '']
    out += _table(['Rule', 'Severity', 'Target', 'Finding'],
                  [[f['ruleId'], f['severity'], f['targetName'], f['description']]
                   for f in result['findings'] if f['estate'] == 'cross'])
    out += ['', '### Recommendations', '']
    out += _table(['Rule', 'Target', 'Recommendation'],
                  [[f['ruleId'], f['targetName'], f['recommendation']]
                   for f in result['findings']
                   if f['estate'] == 'cross' and f['recommendation']])
    out += ['', sequence_markdown(sequence(graph)).replace('# Modernisation sequence',
                                                           '## Modernisation sequence')]
    out += ['', '## Interpretation', '',
            '<!-- LLM: what is the first thing this programme should do, and '
            'what must be settled before it can? Cite the wave-0 items by '
            'name. Do not propose an order the graph does not support. -->', '']
    return '\n'.join(out) + '\n'


def generate_all(graph: Graph) -> Dict[str, str]:
    return {
        'Step00_ESTATE_FEDERATION_REPORT.md': step00_federation(graph),
        'Step01_CROSS_ESTATE_DEPENDENCY_REPORT.md': step01_dependency(graph),
        'Step02_END_TO_END_RISK_AND_SEQUENCE_REPORT.md': step02_risk_and_sequence(graph),
    }
